from pydantic import BaseModel
from typing import List, Optional
import enum
from datetime import date, datetime # Added datetime

class UserRole(str, enum.Enum):
    admin = "admin"
    tesorero = "tesorero"
    comision = "comision"
    profesor = "profesor"
    socio = "socio"
    superadmin = "superadmin"

class MemberBase(BaseModel):
    first_name: str
    last_name: str
    email: str
    phone: Optional[str] = None
    dni: Optional[str] = None
    birth_date: Optional[date] = None

class MemberCreate(MemberBase):
    pass

class MemberUpdate(MemberBase):
    is_active: Optional[bool] = None

class ActivityBase(BaseModel):
    name: str
    monthly_cost: float
    profesor_id: Optional[int] = None

class ActivityCreate(ActivityBase):
    pass

class Activity(ActivityBase):
    id: int
    club_id: int
    profesor: Optional["User"] = None
    class Config:
        from_attributes = True

class Member(MemberBase):
    id: int
    is_active: bool
    activities: List[Activity] = []
    class Config:
        from_attributes = True

class MemberPage(BaseModel):
    items: List[Member]
    total: int

class PaymentBase(BaseModel):
    amount: float
    payment_date: date
    payment_method: Optional[str] = None
    receipt_url: Optional[str] = None

class PaymentCreate(PaymentBase):
    pass

class Payment(PaymentBase):
    id: int
    debt_id: int
    receipt_url: Optional[str] = None

    class Config:
        from_attributes = True

class UserBase(BaseModel):
    email: str

# New schema for superadmin creating a club's admin user
class SuperadminCreateClubUser(UserBase):
    club_name: str
    recovery_email: str

# Existing UserCreate (removed password, which will be generated)
class UserCreate(UserBase):
    # password: str  # Password will be generated by the system
    club_name: str
    recovery_email: str # Superadmin should provide this

class UserCreateByAdmin(BaseModel):
    email_local_part: str
    password: str
    role: UserRole
    recovery_email: Optional[str] = None # Added for admin creating users

class UserUpdateByAdmin(BaseModel):
    role: Optional[UserRole] = None
    is_active: Optional[bool] = None

class SuperadminUserUpdate(BaseModel):
    recovery_email: Optional[str] = None
    role: Optional[UserRole] = None
    is_active: Optional[bool] = None

class ClubUpdate(BaseModel):
    base_fee: float

class SuperadminClubUpdate(BaseModel):
    name: Optional[str] = None
    base_fee: Optional[float] = None
    is_active: Optional[bool] = None

class Club(BaseModel):
    id: int
    name: str
    base_fee: Optional[float] = None
    email_domain: Optional[str] = None
    logo_url: Optional[str] = None # URL or path to the club's logo
    is_active: bool
    class Config:
        from_attributes = True

class User(UserBase):
    id: int
    is_active: bool
    role: UserRole
    club: Optional[Club] = None
    recovery_email: Optional[str] = None 
    force_password_change: Optional[bool] = False # Made optional
    password_reset_token: Optional[str] = None 
    password_reset_expires: Optional[datetime] = None 
    class Config:
        from_attributes = True

class ClubCreationResponse(BaseModel):
    club: Club
    admin_user: User
    temporary_password: str

class Token(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str

class RefreshTokenRequest(BaseModel):
    refresh_token: str

class TokenResponseWithForceChange(Token):
    force_password_change: bool = False

class TokenData(BaseModel):
    email: str | None = None

class DebtGenerationRequest(BaseModel):
    month: str # Expected format: YYYY-MM

class DebtItemBase(BaseModel):
    description: str
    amount: float
    activity_id: Optional[int] = None

class DebtItem(DebtItemBase):
    id: int
    class Config:
        from_attributes = True

class DebtBase(BaseModel):
    month: date
    total_amount: float
    is_paid: bool

class Debt(DebtBase):
    id: int
    member_id: int
    items: List[DebtItem] = []
    payments: List[Payment] = []
    class Config:
        from_attributes = True

class ManualChargeCreate(BaseModel):
    member_id: int
    date: date
    description: str
    amount: float

# --- Schemas for Member Account Statement ---
class TransactionType(str, enum.Enum):
    DEBT = "debt"
    PAYMENT = "payment"

class StatementItem(BaseModel):
    transaction_date: date
    transaction_type: TransactionType
    concept: str
    amount: float
    balance: float
    debt_id: int

class MemberStatement(BaseModel):
    items: List[StatementItem]
    final_balance: float

# --- Schemas for Categories ---
class CategoryType(str, enum.Enum):
    INCOME = "income"
    EXPENSE = "expense"

class CategoryBase(BaseModel):
    name: str
    type: CategoryType

class CategoryCreate(CategoryBase):
    pass

class CategoryUpdate(BaseModel):
    name: Optional[str] = None
    type: Optional[CategoryType] = None

class Category(CategoryBase):
    id: int
    club_id: int
    class Config:
        from_attributes = True

# --- Schemas for Club Transactions ---
class ClubTransactionBase(BaseModel):
    transaction_date: date
    description: str
    amount: float
    type: CategoryType # Use CategoryType enum for transaction type
    payment_method: Optional[str] = None
    category_id: Optional[int] = None
    activity_id: Optional[int] = None
    receipt_url: Optional[str] = None

class ClubTransactionCreate(BaseModel):
    transaction_date: date
    description: str
    amount: float
    type: CategoryType
    category_id: Optional[int] = None # Category is optional for creation

class ClubTransaction(ClubTransactionBase):
    id: int
    user_id: int
    club_id: int
    activity: Optional[Activity] = None
    class Config:
        from_attributes = True

class ClubTransactionPage(BaseModel):
    items: List[ClubTransaction]
    total: int

class Balance(BaseModel):
    total: float
    breakdown: dict[str, float]

# --- Schemas for Password Management ---
class PasswordChange(BaseModel):
    current_password: Optional[str] = None # Made optional
    new_password: str

class PasswordResetRequest(BaseModel):
    email: str # The user's login email (e.g., admin@club.com)

class PasswordReset(BaseModel):
    token: str
    new_password: str

class AdminPasswordChange(BaseModel):
    new_password: str

# --- Schemas for Reports ---
class MonthlyBalanceItem(BaseModel):
    month: int
    month_name: str
    income: float
    expense: float
    balance: float

class IncomeVsExpensesReport(BaseModel):
    items: List[MonthlyBalanceItem]
    annual_income: float
    annual_expense: float
    annual_balance: float

class CategoryTotalItem(BaseModel):
    category: str
    total: float

class CategoryDistributionReport(BaseModel):
    income_by_category: List[CategoryTotalItem]
    expense_by_category: List[CategoryTotalItem]

class StudentAccountStatus(BaseModel):
    member_id: int
    first_name: str
    last_name: str
    dni: Optional[str] = None
    balance: float

class ProfessorStudentReport(BaseModel):
    students: List[StudentAccountStatus]
