"""Add activity_id to DebtItem and ClubTransaction

Revision ID: 40201c72e8f5
Revises: 1f0f9aa26b11
Create Date: 2025-11-19 00:53:14.450704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40201c72e8f5'
down_revision: Union[str, Sequence[str], None] = '1f0f9aa26b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_transactions', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'club_transactions', 'activities', ['activity_id'], ['id'])
    op.add_column('debt_items', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'debt_items', 'activities', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debt_items', type_='foreignkey')
    op.drop_column('debt_items', 'activity_id')
    op.drop_constraint(None, 'club_transactions', type_='foreignkey')
    op.drop_column('club_transactions', 'activity_id')
    # ### end Alembic commands ###
