"""Change member_type to String to fix enum issue

Revision ID: 55084a92284a
Revises: 94cc5a618959
Create Date: 2026-01-28 23:25:37.369991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55084a92284a'
down_revision: Union[str, Sequence[str], None] = '94cc5a618959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'member_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'member_type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
