"""Add password recovery fields to User model

Revision ID: 5abf96afbc03
Revises: 40201c72e8f5
Create Date: 2025-11-24 15:09:14.180810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5abf96afbc03'
down_revision: Union[str, Sequence[str], None] = '40201c72e8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['recovery_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'recovery_email')
    # ### end Alembic commands ###
