"""Remove unique constraint from recovery_email

Revision ID: 641ba21b6968
Revises: 5abf96afbc03
Create Date: 2025-11-24 21:51:27.064128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641ba21b6968'
down_revision: Union[str, Sequence[str], None] = '5abf96afbc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_recovery_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_recovery_email_key'), 'users', ['recovery_email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
