"""Add profesor relationship to Activity

Revision ID: 85cf940e598f
Revises: 641ba21b6968
Create Date: 2026-01-18 20:05:06.313149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cf940e598f'
down_revision: Union[str, Sequence[str], None] = '641ba21b6968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('profesor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'users', ['profesor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'profesor_id')
    # ### end Alembic commands ###
